# Generated by Django 4.0.3 on 2022-03-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_ann', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ann', models.CharField(blank=True, max_length=255, null=True)),
                ('active_flg', models.BooleanField(blank=True, null=True)),
                ('day_ann', models.DateField(blank=True, null=True)),
                ('id_pateint', models.CharField(blank=True, max_length=255, null=True)),
                ('id_file', models.CharField(blank=True, max_length=255, null=True)),
                ('observ', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
