# Generated by Django 4.0.3 on 2022-03-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_alter_annotation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_frame', models.CharField(blank=True, max_length=255, null=True)),
                ('day_ann', models.DateField(blank=True, null=True)),
                ('id_pateint', models.CharField(blank=True, max_length=255, null=True)),
                ('id_file', models.CharField(blank=True, max_length=255, null=True)),
                ('observ', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
