# Generated by Django 4.0.3 on 2022-03-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_pred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='title',
            new_name='frame',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='title_ann',
            new_name='name_video',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='active_flg',
        ),
        migrations.AddField(
            model_name='pred',
            name='frame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pred',
            name='name_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
