# Generated by Django 4.0.3 on 2022-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0005_annotation_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
