# Generated by Django 4.0.1 on 2022-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0007_delete_pred_remove_annotation_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='label_pk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
